language: ruby
rvm: 2.2.3
cache: [bundler, apt]

before_install:
  - sudo apt-get install libicu-dev

script: bundle exec rake

notifications:
  webhooks:
    - https://idobata.io/hook/6a98db40-ac68-45ec-a1b4-d8dd5851c2e3
